theme: fullwidth
custom_categories:
  - name: "Basic Types"
    children:
      - "NoteNumber"
      - "Frequency"
      - "Pitch"
  - name: "Collections"
    children:
      - "Dyad"
      - "Collection"
      - "intervals"
      - "dyads"
  - name: "Intervals"
    children:
      - "OrderedInterval"
      - "UnorderedInterval"
  - name: "Tuning Systems"
    children:
      - "TuningSystem"
